[package]
name = "total-supply"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { workspace = true }
polkavm-derive = { workspace = true }
pvq-program = { workspace = true }
